Repository RandomUserIK/HomesFromArchitectsWebPage-backend, pull requests merged in 2021-05, with the labels that each got.

#16 HFA-31-FIX
  src/main/java/sk/hfa/configuration/security/HfaSecurityConfiguration.java
Labels: bug

#17 HFA-61
  src/main/java/sk/hfa/configuration/security/filters/AuthorizationFilter.java
  src/main/java/sk/hfa/projects/domain/CommonProject.java
  src/main/java/sk/hfa/projects/domain/IndividualProject.java
  src/main/java/sk/hfa/projects/domain/InteriorDesignProject.java
  src/main/java/sk/hfa/projects/domain/Project.java
  src/main/java/sk/hfa/projects/domain/TextSection.java
  src/main/java/sk/hfa/projects/domain/repositories/ProjectRepository.java
  src/main/java/sk/hfa/projects/services/ImageService.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/CommonProjectRequest.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/IndividualProjectRequest.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/InteriorProjectRequest.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/ProjectRequest.java
  src/main/java/sk/hfa/startup/DummyIndividualProjectRunner.java
Labels: enhancement, refactor

#18 Hfa 79 Odosielanie objednávkového formulára na email
  src/main/java/sk/hfa/configuration/security/HfaSecurityConfiguration.java
  src/main/java/sk/hfa/contactform/web/ContactController.java
  src/main/java/sk/hfa/email/service/EmailService.java
  src/main/java/sk/hfa/email/service/interfaces/IEmailService.java
  src/main/java/sk/hfa/email/service/utils/ContactEmailBuilder.java
  src/main/java/sk/hfa/email/service/utils/EmailTextBuilder.java
  src/main/java/sk/hfa/email/service/utils/OrderEmailBuilder.java
  src/main/java/sk/hfa/form/web/FormController.java
  src/main/java/sk/hfa/form/web/FormControllerAdvice.java
  src/main/java/sk/hfa/form/web/domain/requestbodies/ContactFormRequest.java
  src/main/java/sk/hfa/form/web/domain/requestbodies/OrderFormRequest.java
  src/main/java/sk/hfa/form/web/domain/responsebodies/SubmittedFormMessageResource.java
  src/main/java/sk/hfa/orderform/domain/OrderForm.java
  src/main/java/sk/hfa/orderform/domain/repositories/OrderFormRepository.java
  src/main/java/sk/hfa/orderform/services/OrderFormService.java
  src/main/java/sk/hfa/orderform/services/interfaces/IOrderFormService.java
  src/main/java/sk/hfa/orderform/web/OrderFormController.java
  src/main/java/sk/hfa/orderform/web/domain/responsebodies/CreateOrderMessageResource.java
  src/main/resources/application.properties
Labels: enhancement

#19 Hfa 75
  src/main/java/sk/hfa/form/web/FormController.java
  src/main/java/sk/hfa/projects/web/ImageController.java
  src/main/java/sk/hfa/startup/AdminRunner.java
  src/main/java/sk/hfa/startup/DummyIndividualProjectRunner.java
  src/main/resources/application.properties
  src/main/resources/images/title.png
Labels: bug

#20 HFA-63 Komponent pre kategóriu obsah projektu
  src/main/java/sk/hfa/projects/services/ProjectService.java
  src/main/java/sk/hfa/projects/services/interfaces/IProjectService.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
Labels: enhancement

#22 HFA-32 - Separate application.properties and application.dev.properties
  pom.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
Labels: enhancement

#21 HFA-82 - Formulár pre úpravu katalógového projektu
  src/main/java/sk/hfa/projects/domain/CommonProject.java
  src/main/java/sk/hfa/projects/domain/Project.java
  src/main/java/sk/hfa/projects/services/ProjectService.java
  src/main/java/sk/hfa/projects/services/interfaces/IProjectService.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
  src/main/java/sk/hfa/projects/web/ProjectControllerAdvice.java
  src/main/java/sk/hfa/projects/web/domain/customDeserialization/GarageTypeDeserializer.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/CommonProjectRequest.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/ProjectRequest.java
  src/main/java/sk/hfa/projects/web/domain/responsebodies/DeleteProjectMessageResource.java
  src/main/java/sk/hfa/startup/DummyIndividualProjectRunner.java
  src/main/resources/application.properties
Labels: enhancement

#24 HFA-97 Aktualizácia projektu v admin sekcii
  src/main/java/sk/hfa/projects/services/ImageService.java
  src/main/java/sk/hfa/projects/services/interfaces/IImageService.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
Labels: enhancement

#23 HFA-85
  src/main/java/sk/hfa/auth/domain/throwable/InvalidJwtTokenException.java
  src/main/java/sk/hfa/auth/service/AuthenticationService.java
  src/main/java/sk/hfa/auth/service/AuthorizationService.java
  src/main/java/sk/hfa/auth/service/interfaces/IAuthenticationService.java
  src/main/java/sk/hfa/auth/service/interfaces/IAuthorizationService.java
  src/main/java/sk/hfa/auth/web/AuthenticationController.java
  src/main/java/sk/hfa/auth/web/AuthenticationControllerAdvice.java
  src/main/java/sk/hfa/auth/web/responsebodies/AuthenticationErrorResponse.java
  src/main/java/sk/hfa/auth/web/responsebodies/AuthenticationResponse.java
  src/main/java/sk/hfa/configuration/security/HfaSecurityConfiguration.java
  src/main/java/sk/hfa/configuration/security/cookie/CookieService.java
  src/main/java/sk/hfa/configuration/security/cookie/interfaces/ICookieService.java
  src/main/java/sk/hfa/configuration/security/filters/AuthorizationFilter.java
  src/main/java/sk/hfa/projects/services/ProjectService.java
  src/main/java/sk/hfa/projects/services/interfaces/IProjectService.java
  src/main/java/sk/hfa/projects/web/ImageController.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
  src/main/resources/application.properties
Labels: enhancement, refactor

#25 HFA-101
  src/main/java/sk/hfa/configuration/security/HfaSecurityConfiguration.java
  src/main/java/sk/hfa/configuration/security/filters/AuthorizationFilter.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
  src/main/java/sk/hfa/startup/DummyIndividualProjectRunner.java
  src/main/resources/application.properties
  src/main/resources/title.png
Labels: enhancement

#26 fix(Database character formating): Fix databse character formating
  .travis.yml
  src/main/resources/application.properties
Labels: bug

#27 Hfa 67 - Endpoint pre instagram feed
  src/main/java/sk/hfa/HfaApplication.java
  src/main/java/sk/hfa/crons/InstagramTokenCron.java
  src/main/java/sk/hfa/instagram/domain/InstagramToken.java
  src/main/java/sk/hfa/instagram/domain/repository/InstagramTokenRepository.java
  src/main/java/sk/hfa/instagram/domain/service/InstagramTokenService.java
  src/main/java/sk/hfa/instagram/domain/service/interfaces/IInstagramTokenService.java
  src/main/java/sk/hfa/projects/web/InstagramController.java
  src/main/java/sk/hfa/projects/web/InstagramTokenClient.java
  src/main/java/sk/hfa/projects/web/domain/responsebodies/InstagramBodyResource.java
  src/main/java/sk/hfa/projects/web/domain/responsebodies/InstagramBodyValueResource.java
  src/main/java/sk/hfa/projects/web/domain/responsebodies/InstagramRefreshTokenResource.java
  src/main/java/sk/hfa/projects/web/domain/responsebodies/InstagramTokenMessageResource.java
  src/main/resources/application.properties
Labels: enhancement

#29 HFA-86 - Nastaviť max input length na fronte a backende pre jednotlivé text input fieldy
  src/main/java/sk/hfa/form/web/domain/requestbodies/ContactFormRequest.java
  src/main/java/sk/hfa/form/web/domain/requestbodies/OrderFormRequest.java
  src/main/java/sk/hfa/projects/domain/TextSection.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
  src/main/java/sk/hfa/projects/web/domain/requestbodies/ProjectRequest.java
Labels: enhancement

#30 HFA-104
  src/main/java/sk/hfa/blog/domain/BlogArticle.java
  src/main/java/sk/hfa/blog/domain/BlogArticleDto.java
  src/main/java/sk/hfa/blog/services/BlogService.java
  src/main/java/sk/hfa/blog/web/BlogController.java
  src/main/java/sk/hfa/images/domain/enums/ImageType.java
  src/main/java/sk/hfa/images/domain/repositories/FileSystemRepository.java
  src/main/java/sk/hfa/images/domain/throwable/FetchFileSystemResourceException.java
  src/main/java/sk/hfa/images/domain/throwable/ImageUploadException.java
  src/main/java/sk/hfa/images/services/ImageService.java
  src/main/java/sk/hfa/images/services/interfaces/IImageService.java
  src/main/java/sk/hfa/images/web/ImageController.java
  src/main/java/sk/hfa/images/web/ImageControllerAdvice.java
  src/main/java/sk/hfa/images/web/domain/responsebodies/ImageMessageResource.java
  src/main/java/sk/hfa/images/web/domain/responsebodies/ImageUploadMessageResource.java
  src/main/java/sk/hfa/projects/web/ProjectController.java
Labels: enhancement

#31 HFA-106
  src/main/java/sk/hfa/images/services/ImageService.java
  src/main/java/sk/hfa/projects/services/ProjectService.java
Labels: enhancement
